services:
  - type: web
    name: emotion-analyzer
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: "False"
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"
      - key: TF_NUM_INTRAOP_THREADS
        value: "2"
      - key: TF_NUM_INTEROP_THREADS
        value: "1"
      - key: OMP_NUM_THREADS
        value: "2"
